name: "test for initializer of dotfiles for Linux"

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'bin/**'
      - 'Makefile'
      - 'install.sh'
      - 'Interactive-install.sh'
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        script: ["./brew.sh", "./symlink.sh"]

    steps:
      - uses: actions/checkout@v2
      - name: unit-test of ${{matrix.script}}
        working-directory: ./bin/
        run: ${{matrix.script}}

  init-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: make install

  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: link
        run: make deploy
